printWidth: 120
tabWidth: 2
semi: true
singleQuote: true
trailingComma: 'none'
bracketSpacing: true
arrowParens: 'always'
jsxBracketSameLine: true
plugins:
  - prettier-plugin-svelte
svelteSortOrder: 'styles-markup-scripts'
svelteStrictMode: true
svelteBracketNewLine: false
